name: Discord Events

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
  release:
    types:
      - published

jobs:
  notify-discord:
    uses: ./.github/workflows/discord-notify.yml
    secrets:
      discord_webhook: ${{ secrets.DISCORD_WEBHOOK }}
